version: 2

builds:
  - main: ./cmd/pearcut
    binary: pearcut
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "pearcut_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  use: github-native
